### ISSUE TITLE
TypeError: ('Bad input argument to theano function with name "Vanilla_RNN.py:199"  at index 0(0-based)', 'TensorType(float32, matrix) cannot store a value of dtype float64 without risking loss of precision. 

### ISSUE THREAD

**Issue by andyyuan78** [mohammadpz/Recurrent-Neural-Networks#2]
ubgpu@ubgpu:~/github/Recurrent-Neural-Networks$ 
ubgpu@ubgpu:~/github/Recurrent-Neural-Networks$ sudo python Vanilla_RNN.py 
Using gpu device 0: GeForce GTX 970
Testing model with real outputs
/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_perform_ext.py:133: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *
Buiding model ...
Vanilla_RNN.py:299: UserWarning: The parameter 'updates' of theano.function() expects an OrderedDict, got <type 'dict'>. Using a standard dictionary here results in non-deterministic behavior. You should use an OrderedDict if you are using Python 2.7 (theano.compat.python2x.OrderedDict for older python), or use a list of (shared, update) pairs. Do not just convert your dictionary to this type before the call as the conversion will still be non-deterministic.
  mode = mode)
Training model ...
epoch 1, train loss 0.842026 lr: 0.001000
epoch 2, train loss 0.841860 lr: 0.000999
epoch 3, train loss 0.841732 lr: 0.000998
..........
epoch 399, train loss 0.262864 lr: 0.000672
epoch 400, train loss 0.262817 lr: 0.000671
Traceback (most recent call last):
  File "Vanilla_RNN.py", line 515, in <module>
    test_real()
  File "Vanilla_RNN.py", line 384, in test_real
    guess = model.predict(seq[0])
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 513, in **call**
    allow_downcast=s.allow_downcast)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 131, in filter
    raise TypeError(err_msg, data)
TypeError: ('Bad input argument to theano function with name "Vanilla_RNN.py:199"  at index 0(0-based)', 'TensorType(float32, matrix) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function".', array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218]]))
ubgpu@ubgpu:~/github/Recurrent-Neural-Networks$ git remote -v 
origin  https://github.com/mohammadpz/Recurrent-Neural-Networks.git (fetch)
origin  https://github.com/mohammadpz/Recurrent-Neural-Networks.git (push)
ubgpu@ubgpu:~/github/Recurrent-Neural-Networks$

**Comment by mpezeshki** [comment]
Code is working. You can fix this error by defining `dtype=theano.config.floatX` for numpy arrays.
